version: '3.8'

services:
  browserless:
    image: browserless/chrome
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - MAX_CONCURRENT_SESSIONS=10
      - CONNECTION_TIMEOUT=300000
      - ENABLE_DEBUGGER=true
      - TOKEN=your-secret-token
